# public/admin/config.yml

# 1. Configuração do Backend CUSTOMIZADO (Para usar o Supabase)
backend:
  name: custom # Define o tipo de backend como customizado
  auth_url: /api/cms/auth # O endpoint que faremos para checar a autenticação

display_url: http://localhost:3000

# 2. Configuração de Interface (mantida)
site_url: http://localhost:3000
logo_url: /logo-ceboela-e-alho.jpg
show_preview_links: true
media_folder: 'public/images/uploads' 
public_folder: '/images/uploads'

# 3. Definição da Coleção (Tabela 'posts')
collections:
  - name: 'blog'
    label: 'Blog (Posts)'
    # Aqui, a pasta é apenas um placeholder. O CMS saberá que deve chamar o custom backend.
    folder: 'data/blog' 
    identifier_field: 'slug' 
    fields:
      - { label: 'Título do Post', name: 'title', widget: 'string', required: true }
      - { label: 'Slug (URL)', name: 'slug', widget: 'string', required: true, hint: 'Usado na URL (ex: 5-receitas-faceis)' }
      - { label: 'Data da Criação', name: 'created_at', widget: 'datetime', format: 'YYYY-MM-DDTHH:mm:ssZ', required: true }
      - { label: 'Autor', name: 'author', widget: 'string', default: 'Chef Amigo IA' }
      - { label: 'Excerto (Resumo)', name: 'excerpt', widget: 'string', hint: 'Resumo breve para a listagem da página /blog.' }
      - { label: 'Imagem de Capa', name: 'image_url', widget: 'string', required: false, hint: 'URL da Imagem' }
      - { label: 'Conteúdo', name: 'content', widget: 'markdown', required: true }